# Generated by Django 5.1 on 2024-09-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
