# Generated by Django 5.1 on 2024-10-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_report_reason_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
