# Generated by Django 5.1 on 2024-10-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_report_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('to_edit', 'To Edit'), ('to_publish', 'To Publish'), ('published', 'Published'), ('inactive', 'Inactive')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('to_edit', 'To Edit'), ('to_publish', 'To Publish'), ('published', 'Published'), ('inactive', 'Inactive')], default='draft', max_length=20),
        ),
    ]
