# Generated by Django 5.1 on 2024-10-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_initial'),
        ('posts', '0004_alter_historicalpost_status_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='suscribed_categories',
            field=models.ManyToManyField(blank=True, related_name='suscribed_members', to='posts.category'),
        ),
    ]
