# Generated by Django 5.1 on 2024-09-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='suscribed_categories',
            field=models.ManyToManyField(blank=True, related_name='suscribed_members', to='posts.category'),
        ),
    ]
